### ISSUE TITLE
Generate PR template

### ISSUE THREAD

**Issue by thejourneydude** [drparadoxical/aeon-rebase#2]
In my experience, PR templates provides several benefits to a git repository:

1) Documentation for future developer reference.
2) Makes it easier for code reviewers to review code.
3) Ensures the PR creator reviews their own code before PR submission.

To create a PR template, we can follow [this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) guide.
 
Finally, here is an example of a PR template.

## What issue does your PR solve?
#999999999

## What does your PR do?
Fixes this annoying bug that breaks the code.

## How did you test your solution?
I ran the list of spec tests which all passed. I then attempted to recreate the bug and was unable to do so.

## Is there anything special you've done others should know about?
I had to make some changes to some important code that a lot of people use. 

## Anything else we should know?
None.

**Comment by drparadoxical** [comment]
If this is still necessary, please issue another PR @thejourneydude and we'll discuss it on the PR itself. Otherwise, please just let me know if this is a moot point now and can/should be closed.

**Comment by drparadoxical** [comment]
This issue was moved to drparadoxical/aeon-rebase-1#1
