### ISSUE TITLE
Generate contributing guideline

### ISSUE THREAD

**Issue by firecrypt** [drparadoxical/aeon-rebase#4]
Writing clear commit messages and keeping the scope of each commit limited helps others review the changes incrementally.

See links for examples.
- [Writing good commit messages](https://github.com/erlang/otp/wiki/writing-good-commit-messages)
- [Setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

**Comment by drparadoxical** [comment]
Let's stretch this space out a bit and use it to talk about our general SOP when it comes to development, commits, etc. 

I don't think we're all in yet, though, a couple of people who joined the team but aren't here yet, so will hold off on getting any deeper with said SOP than my brief take on things below.

1. Pull and merge locally before diving in or back in to your work
2. Commit once you've finished a task, again once you've finished writing tests, again once you've worked out any kinks from running said test
3. Push only once aforementioned commits occur, and per task - so we can keep pushes and tasks 1:1

I come from the old world of SVN, so there's likely some new world SOP I may be oblivious too, go easy on me, I'll learn. (for example, what Github calls a pull request is what I'd call a branch, but I'm thinking I'll need to be educated here, as I don't want my ignorance to slow us down or screw any of you up)

**Comment by firecrypt** [comment]
@drparadoxical The development flow is quite different, but I think it ends up working better than SVN. SVN is centralized and git is distributed...we just happen to be using a centralized service and saying that's the official one.

The fundamental difference is that everyone can get a copy and do whatever the hell they want. Add stuff, break shit. Whatever. You treat one branch (usually the master) as the official release branch that shouldn't be broken. Devs issue pull requests from the copies they have in order to merge in the work they've committed. Requests to merge in new work are heavily (well...they should be) scrutinized before the merge is complete. Github will check to see if the merge can be completed without conflicts. If it can, no problem. If not, it's usually up to the dev to make sure all conflicts are resolved so the merge completes cleanly.

Addressing your points:
1. That shouldn't be a problem because we all have our own copies.
2. Having said that, the PR issued should be [rebased](https://git-scm.com/docs/git-rebase) and cleaned up via `git rebase -i HEAD~{NUM_COMMITS}`. If you want the commits broken into those categories, it is certainly possible.
3. Each task/feature would ideally have its own branch. That way we can keep it 1:1 and have multiple commits. For fixes, I usually create a branch called `firecrypt/fixes` and throw stuff in their until I have enough for a PR. That way, I don't pollute other PRs specific to features.

Some git reference material:
- [Git vs SVN](https://git.wiki.kernel.org/index.php/GitSvnComparison) (info is a little outdated)
- [What's a branch](https://git-scm.com/book/en/v1/Git-Branching-What-a-Branch-Is)
- [Git branching and merging](https://git-scm.com/book/be/v2/Git-Branching-Basic-Branching-and-Merging)
- [Git branching guidance](https://docs.microsoft.com/en-us/vsts/git/concepts/git-branching-guidance) (I don't agree with how Microsoft handles releases, but I understand why they would do it that way)
- [Rewriting git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) (should only be done on dev branches that public doesn't pull from)

Again, I'm just offering up suggestions. We can do whatever the team decides, but this is what has worked well for me in the past.

**Comment by drparadoxical** [comment]
Ah, how clever. I see how some of this bent functionality is actually meant to serve the developers better. Interesting. 

I'll review those links, but am starting to better understand how and why one would want firecrypt/fixes to begin with, where precisely CI benefits us in the pipeline re: git/Github (PR->merge->team scrutiny->CI test/verify->passed->merge complete). 

Well how about that. Fancy.

**Comment by drparadoxical** [comment]
When it comes to addressing my points, I first want to make sure everyone's here. While anyone can review discussions held and catch themselves up to speed, better to do a bit of informal intake and let ourselves train ourselves up before we start moving fast and breaking shit, as you say.

**Comment by devopsralf** [comment]
@drparadoxical Checking in as per your email. Looks like theres alot to go through and hello to the rest of the folks here.

**Comment by drparadoxical** [comment]
Welcome. Please do read up, I've been doing the same this fine evening. We'll be gathering 'round the fire for a bit. I'll know when everyone's here, and we'll go from there.

**Comment by drparadoxical** [comment]
This issue is resolved by way of having now inherited the CONTRIBUTING.md when we cloned the Monero tag as per Smooth's guidelines in his recent Reddit post.

**Comment by drparadoxical** [comment]
This issue was moved to drparadoxical/aeon-rebase-1#8
