### ISSUE TITLE
What, Where, Who, How - Breaking Some Ground

### ISSUE THREAD

**Issue by drparadoxical** [drparadoxical/aeon-rebase#6]
Team, 

Looks like some of us had the gumption, full of piss a vinegar and all, and got some balls rolling. Let's get some basics down so we know where and what for what we've currently got. 

1. First, we're missing some people, and I'm tracking them down and making sure they're in on these repositories as collaborators, unless that's just not necessary these days - seems like everyone was able to dive right in just fine. 
2. Past this ticket, unless a discussion is related to a ticket, we'll try to compartmentalize discussion in gitter, unless someone has a better idea. If not, I'll create the aeon-rebase/ and aeon-webwallet/ gitter channels accordingly, and then rooms and discussions can be sectioned off and managed from there. 
3. No one spends money on this thing - I've got an operating budget for us already that's going to pay for whatever bells and whistles and services we need. When you need something, just say it, I don't want anyone cannibalizing their personal budgets just to get something done.
   1. On this topic, making sure we've access to Github CI tools is on my to-do list, unless anyone has any objections or a better approach. We'll make sure unit and integration tasting is a bit more rigid and predictable and lean on CI accordingly, but again, unless someone objects or has a better approach. 
4. Currently, space is carved out in Firebase and GCP, and this team will be brought into that space as well, allowing us all access to and management of whatever it is that's needed. Again, operating budget handles the cost of, say, a VM with a node is propped up as a node for testing. 
   1. I'll need suggestions from you on how to ensure the account space may be abandoned, and is not a requirement, because no single person needs to be the administrator for anything at the end of the day - no captures, no control, everything's open sourced, everything's on the up and up. 
5. We're currently determining the best place to begin our work, and right now it seems there's a consensus that we begin rebasing from a clone of the Monero tree, determining now whether that's the v0.11.1.0 tag, or current working master, in a discussion in another one of the tickets. 
6. Over the next few days, I'll be ripping some order away from chaos and pulling together a project management plan and set of requirements currently known to be a part of the rebase work, where our general SOP will be defined. It seems some decisions have already been made, which is great, and the SPMP and SRS I'm drafting is focused less on what can be done, more on how things should be done. For example, testing, I see, is already a topic of discussion by team members - but before we dive in and rip things apart and run into issues with testing, we'll step back and determine, discuss, decide how precisely we get from here to an AEON testnet to begin with.
   1. This point, generally speaking, will be easier to approach and discuss, once eyeballs are on actual SPMP and SRS documents, FYI, and it is then and there where we'll be able to discuss and decide how we're triaging, developing, testing, merging, defining, designing, discussing, and so on. 

I'll stop short here and open things up for discussion, and as per my first point above, need to focus on ensuring everyone wanting to be involved is here before proceeding any further myself.

**Comment by guzzijones** [comment]
I am ready to dive in and help any way I can.  I stick to mostly fringe work on monero since i do have a day job..  I am currently getting myself up to speed on unit testing and mocking.  I am very familiar with git.  I have full confidence in you.  I presume a solid plan is forthcoming.

**Comment by drparadoxical** [comment]
Welcome. Thank you. Indeed it is. 

I'll let me actions and efforts determine whether I'm deserving of your confidence. 

Don't quit your day job, but if you do, that's fine, one of my corporations will simply hire you. 

I take things pretty seriously, and with a team of people willing to fight together and with me - doubly so.

**Comment by qskousen** [comment]
/u/exuant_bits from Reddit here, @drparadoxical, signing in. So others know, @drparadoxical and I have been talking on Reddit about what I can bring to the table. I am a full stack web dev, php 7+ years, golang (now preferred language) 1+ years. Like guzzijones I do have a full time job and a side project that I am aiming on launching before the end of the year, but I am here to help where I can. From conversations with @drparadoxical  it sounds like that will be mostly with the web wallet.

**Comment by devopsralf** [comment]
@drparadoxical Would you mind creating a desktop repo as well. I am making some progress in that. Or once you have the time to add us a collaborators I can do it. Also hi @qskousen , I'll be pitching in my work for the web wallet as well.

**Comment by drparadoxical** [comment]
Damn fine idea. For anyone who wants to introduce themselves similarly, please and by all means. 

/u/drparadoxically here. I'm a genius billionaire philanthropist with decades of experience and knowledge, and haven't had a job for as long as I can remember, I just own a conglomerate is all. 

I've built dozens of companies, designed and developed and deployed systems and software locally, nationally, globally, established incubators and facilitated economic development, and outright refuse to be an investor because I've a rule about never buying another's equity, and never squeezing blood and returns out of a startup raddish. 

For a time, and only if you'll allow me to do so, I'll have your back, and my resources will be at your disposal, so long as no one's anonymity is ever threatened. I'll not stand for that, not now or ever. But again, I don't want anyone hurting themselves just to help here, not when you really just don't have to. Not on my watch, at least.

**Comment by drparadoxical** [comment]
And of course I'm just kidding, I'm not really a billionaire, not there yet unfortunately. 

All else, true.

**Comment by drparadoxical** [comment]
@devopsralf, can't pull the trigger on the desktop repo just yet, but as per our discussion on Reddit, I added it to the planning document I'm working in and on, because I'll run that by Smooth and Katie to see if they want to make it a bounty as well. 

In the event it becomes its own bounty, best you just take your work and cash in, in my opinion, unless it's something you believe the team can take on and subsequent bounty be absorbed and divvied up among the team members equally. 

Cart before the horse, though - again, it's not a bounty yet, so let's first see where things go, alright?

**Comment by devopsralf** [comment]
@drparadoxical Got it. I read that a late last night so I did not fully absorb that tidbit. Completely makes sense at this point. Onward with the web wallet then.

**Comment by devopsralf** [comment]
As for my full intro;

I am a network and systems administrator by day. I live in the infrastructure world managing a small IT team and two data centers. I also run an AEON mining pool and participate in global hackathons regularly.

**Comment by drparadoxical** [comment]
Gitter badge has been added to the README.md for aeon-rebase, taking you to aeon-rebase/Lobby, so we've got two separate communities, both for aeon-project-planning and aeon-rebase. I'll create a third for the aeon-webwallet after pushing in the current state of work for said web wallet, to house discussions related to web wallet. Redundant department of Redundancy.

**Comment by devopsralf** [comment]
I also hit the comment button when posting mid thought...its an acquired skill. On the coding side I do C# and lots of scripting with PowerShell. I've been diving into node the last few years as well as hardware design aka nodemcu, arduino etc. My last project won me a trip to China to compete with other like minded individuals. Ok now I'm done!

**Comment by drparadoxical** [comment]
and thank you @devopsralf, glad to have you aboard. 

Now, this sure does feel like herding damn cats. With too many systems, how precisely does one ensure all team members know a team conversation is occurring in a specific location...

I'm thinking I'll broadcast what's going on here and in the gitter channels, and then at least everyone will know where we currently are, what comes next, what our starting point is, what to expect, etc.

**Comment by thejourneydude** [comment]
A little bit about myself:

Software engineer (5+ years) with experience in a little bit of everything: Ruby, JS, Swift, C#, etc. etc. I'm about to start a full-time 6 month project in a week or two and have my music on the side. Outside of that, Aeon, I am at your beck and call.

**Comment by drparadoxical** [comment]
https://github.com/drparadoxical/aeon-project-planning/issues/3

**Comment by drparadoxical** [comment]
@devopsralf - marry in, makes travel between here and China much easier, in my experience.

@thejourneydude - I'm making note of the fact you used the word 'stuck' in your most recent comment, and will bring it up again later on down the road, so we can see if there's anything that can be done about it.

**Comment by routed27** [comment]
It wasn't my intent to be fashionably late to the fire but glad to be here.  I see that this ad-hoc assemble can not only produce the long desired Aeon code re-base but help define Aeons future. My goal is to help you get there.

**Comment by drparadoxical** [comment]
Ground broken, we all seem to be situating ourselves just fine, closing this out now.

**Comment by drparadoxical** [comment]
This issue was moved to drparadoxical/aeon-rebase-1#10
