### ISSUE TITLE
do me first. update commit message. verify access

### ISSUE THREAD

**Issue by guzzijones** [drparadoxical/aeon-rebase#9]
Please adjust the commit log message to readme update. Thanks

**Comment by drparadoxical** [comment]
Alright, @routed27, as @guzzijones suggested, force pushed that commit message just now, heads up sir.

**Comment by guzzijones** [comment]
Awesome. Thanks team.

**Comment by drparadoxical** [comment]
This issue was moved to drparadoxical/aeon-rebase-1#12
